#!/bin/bash

# This is a file called "pre-install" in the root of the project

if [[ "$EAS_BUILD_PLATFORM" == "android" ]]; then
  echo "Run commands for Android builds here"
  echo $GOOGLE_SERVICES_BASE64 | base64 --decode > ./google-services.json
elif [[ "$EAS_BUILD_PLATFORM" == "ios" ]]; then
  echo "Run commands for iOS builds here"
  echo $GOOGLE_SERVICE_INFO_BASE64 | base64 --decode > ./GoogleService-Info.plist
fi
