name: Expo Setup
description: Setup Expo with the provided token
inputs:
  token:
    description: "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
    required: true

runs:
  using: 'composite'

  steps:
    - name: ☑️ Check for EXPO_TOKEN
      shell: bash
      env:
        EXPO_TOKEN: ${{ inputs.token }}
      run: |
        if [ -z "${{ inputs.token }}" ]; then
          echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
          exit 1
        fi

    - name: 🏗 Setup EAS
      uses: expo/expo-github-action@v8
      env:
        EXPO_TOKEN: ${{ inputs.token }}
      with:
        eas-version: latest
        expo-version: latest
        token: ${{ inputs.token }}
