name: Run TODO to Issue

# on:
#   push:
#     branches:
#       - main

on: workflow_call

jobs:
  find-todos:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: Find TODOs
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 📋 TODO to Issue
        uses: alstr/todo-to-issue-action@v4
